# platform :ios, '10.0'

target 'socialNetwork' do
  use_frameworks!

  # Pods for socialNetwork

    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Kingfisher'
    pod 'FirebaseFirestoreSwift'

end
